package ddl;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 权限列表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AccessListDb implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private String id;

	/** 用户权限表主键. */
	private String linkedroleid;

	/** 权限名称. */
	private String rolename;

	/** 关联菜单表ID. */
	private String linkedmenuid;

	/** 菜单名称. */
	private String menuname;

	/** 访问URL. */
	private String menuurl;

	/** 创建人(系统用户名称). */
	private String createby;

	/** 创建时间. */
	private String createtime;

	/** 备注. */
	private String comments;

	/** The set of 组权限表. */
	private Set<GroupAccessDb> groupAccessSet;

	/**
	 * Constructor.
	 */
	public AccessListDb() {
		this.groupAccessSet = new HashSet<GroupAccessDb>();
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 用户权限表主键.
	 * 
	 * @param linkedroleid
	 *            用户权限表主键
	 */
	public void setLinkedroleid(String linkedroleid) {
		this.linkedroleid = linkedroleid;
	}

	/**
	 * Get the 用户权限表主键.
	 * 
	 * @return 用户权限表主键
	 */
	public String getLinkedroleid() {
		return this.linkedroleid;
	}

	/**
	 * Set the 权限名称.
	 * 
	 * @param rolename
	 *            权限名称
	 */
	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	/**
	 * Get the 权限名称.
	 * 
	 * @return 权限名称
	 */
	public String getRolename() {
		return this.rolename;
	}

	/**
	 * Set the 关联菜单表ID.
	 * 
	 * @param linkedmenuid
	 *            关联菜单表ID
	 */
	public void setLinkedmenuid(String linkedmenuid) {
		this.linkedmenuid = linkedmenuid;
	}

	/**
	 * Get the 关联菜单表ID.
	 * 
	 * @return 关联菜单表ID
	 */
	public String getLinkedmenuid() {
		return this.linkedmenuid;
	}

	/**
	 * Set the 菜单名称.
	 * 
	 * @param menuname
	 *            菜单名称
	 */
	public void setMenuname(String menuname) {
		this.menuname = menuname;
	}

	/**
	 * Get the 菜单名称.
	 * 
	 * @return 菜单名称
	 */
	public String getMenuname() {
		return this.menuname;
	}

	/**
	 * Set the 访问URL.
	 * 
	 * @param menuurl
	 *            访问URL
	 */
	public void setMenuurl(String menuurl) {
		this.menuurl = menuurl;
	}

	/**
	 * Get the 访问URL.
	 * 
	 * @return 访问URL
	 */
	public String getMenuurl() {
		return this.menuurl;
	}

	/**
	 * Set the 创建人(系统用户名称).
	 * 
	 * @param createby
	 *            创建人(系统用户名称)
	 */
	public void setCreateby(String createby) {
		this.createby = createby;
	}

	/**
	 * Get the 创建人(系统用户名称).
	 * 
	 * @return 创建人(系统用户名称)
	 */
	public String getCreateby() {
		return this.createby;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createtime
	 *            创建时间
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public String getCreatetime() {
		return this.createtime;
	}

	/**
	 * Set the 备注.
	 * 
	 * @param comments
	 *            备注
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * Get the 备注.
	 * 
	 * @return 备注
	 */
	public String getComments() {
		return this.comments;
	}

	/**
	 * Set the set of the 组权限表.
	 * 
	 * @param groupAccessSet
	 *            The set of 组权限表
	 */
	public void setGroupAccessSet(Set<GroupAccessDb> groupAccessSet) {
		this.groupAccessSet = groupAccessSet;
	}

	/**
	 * Add the 组权限表.
	 * 
	 * @param groupAccess
	 *            组权限表
	 */
	public void addGroupAccess(GroupAccessDb groupAccess) {
		this.groupAccessSet.add(groupAccess);
	}

	/**
	 * Get the set of the 组权限表.
	 * 
	 * @return The set of 组权限表
	 */
	public Set<GroupAccessDb> getGroupAccessSet() {
		return this.groupAccessSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AccessListDb other = (AccessListDb) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
