package ddl;

import java.io.Serializable;

/**
 * Model class of 组权限表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GroupAccessDb implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private String id;

	/** 组表. */
	private SystemGroupDb linkedgroupsystemGroup;

	/** 名称. */
	private String name;

	/** 权限列表. */
	private AccessListDb linkedaccesslistaccessList;

	/** 关联表名. */
	private String linkedtable;

	/** 关联表ID. */
	private String linkedid;

	/** 创建人(系统用户名称). */
	private String createby;

	/** 创建时间. */
	private String createtime;

	/** 备注. */
	private String comments;

	/**
	 * Constructor.
	 */
	public GroupAccessDb() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 组表.
	 * 
	 * @param linkedgroupsystemGroup
	 *            组表
	 */
	public void setLinkedgroupsystemGroup(SystemGroupDb linkedgroupsystemGroup) {
		this.linkedgroupsystemGroup = linkedgroupsystemGroup;
	}

	/**
	 * Get the 组表.
	 * 
	 * @return 组表
	 */
	public SystemGroupDb getLinkedgroupsystemGroup() {
		return this.linkedgroupsystemGroup;
	}

	/**
	 * Set the 名称.
	 * 
	 * @param name
	 *            名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 名称.
	 * 
	 * @return 名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 权限列表.
	 * 
	 * @param linkedaccesslistaccessList
	 *            权限列表
	 */
	public void setLinkedaccesslistaccessList(AccessListDb linkedaccesslistaccessList) {
		this.linkedaccesslistaccessList = linkedaccesslistaccessList;
	}

	/**
	 * Get the 权限列表.
	 * 
	 * @return 权限列表
	 */
	public AccessListDb getLinkedaccesslistaccessList() {
		return this.linkedaccesslistaccessList;
	}

	/**
	 * Set the 关联表名.
	 * 
	 * @param linkedtable
	 *            关联表名
	 */
	public void setLinkedtable(String linkedtable) {
		this.linkedtable = linkedtable;
	}

	/**
	 * Get the 关联表名.
	 * 
	 * @return 关联表名
	 */
	public String getLinkedtable() {
		return this.linkedtable;
	}

	/**
	 * Set the 关联表ID.
	 * 
	 * @param linkedid
	 *            关联表ID
	 */
	public void setLinkedid(String linkedid) {
		this.linkedid = linkedid;
	}

	/**
	 * Get the 关联表ID.
	 * 
	 * @return 关联表ID
	 */
	public String getLinkedid() {
		return this.linkedid;
	}

	/**
	 * Set the 创建人(系统用户名称).
	 * 
	 * @param createby
	 *            创建人(系统用户名称)
	 */
	public void setCreateby(String createby) {
		this.createby = createby;
	}

	/**
	 * Get the 创建人(系统用户名称).
	 * 
	 * @return 创建人(系统用户名称)
	 */
	public String getCreateby() {
		return this.createby;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createtime
	 *            创建时间
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public String getCreatetime() {
		return this.createtime;
	}

	/**
	 * Set the 备注.
	 * 
	 * @param comments
	 *            备注
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * Get the 备注.
	 * 
	 * @return 备注
	 */
	public String getComments() {
		return this.comments;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		GroupAccessDb other = (GroupAccessDb) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
