package ddl;

import java.io.Serializable;

/**
 * Model class of 生产用户详情表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class LiveAccountDetailsDb implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private String id;

	/** 生产用户管理表. */
	private LiveAccountDb accountliveAccount;

	/** 关联详情表名. */
	private String linkedtable;

	/** 关联详情表ID. */
	private String linkedid;

	/** 创建时间. */
	private String createtime;

	/** 备注. */
	private String comments;

	/**
	 * Constructor.
	 */
	public LiveAccountDetailsDb() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 生产用户管理表.
	 * 
	 * @param accountliveAccount
	 *            生产用户管理表
	 */
	public void setAccountliveAccount(LiveAccountDb accountliveAccount) {
		this.accountliveAccount = accountliveAccount;
	}

	/**
	 * Get the 生产用户管理表.
	 * 
	 * @return 生产用户管理表
	 */
	public LiveAccountDb getAccountliveAccount() {
		return this.accountliveAccount;
	}

	/**
	 * Set the 关联详情表名.
	 * 
	 * @param linkedtable
	 *            关联详情表名
	 */
	public void setLinkedtable(String linkedtable) {
		this.linkedtable = linkedtable;
	}

	/**
	 * Get the 关联详情表名.
	 * 
	 * @return 关联详情表名
	 */
	public String getLinkedtable() {
		return this.linkedtable;
	}

	/**
	 * Set the 关联详情表ID.
	 * 
	 * @param linkedid
	 *            关联详情表ID
	 */
	public void setLinkedid(String linkedid) {
		this.linkedid = linkedid;
	}

	/**
	 * Get the 关联详情表ID.
	 * 
	 * @return 关联详情表ID
	 */
	public String getLinkedid() {
		return this.linkedid;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createtime
	 *            创建时间
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public String getCreatetime() {
		return this.createtime;
	}

	/**
	 * Set the 备注.
	 * 
	 * @param comments
	 *            备注
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * Get the 备注.
	 * 
	 * @return 备注
	 */
	public String getComments() {
		return this.comments;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		LiveAccountDetailsDb other = (LiveAccountDetailsDb) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
