package ddl;

import java.io.Serializable;

/**
 * Model class of 系统运行日志表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SystemRunningLogDb implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private String id;

	/** 开始时间. */
	private String begintime;

	/** 故障内容. */
	private String description;

	/** 记录机器IP. */
	private String createip;

	/** 结束时间. */
	private String endtime;

	/** 备注. */
	private String comments;

	/**
	 * Constructor.
	 */
	public SystemRunningLogDb() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 开始时间.
	 * 
	 * @param begintime
	 *            开始时间
	 */
	public void setBegintime(String begintime) {
		this.begintime = begintime;
	}

	/**
	 * Get the 开始时间.
	 * 
	 * @return 开始时间
	 */
	public String getBegintime() {
		return this.begintime;
	}

	/**
	 * Set the 故障内容.
	 * 
	 * @param description
	 *            故障内容
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the 故障内容.
	 * 
	 * @return 故障内容
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the 记录机器IP.
	 * 
	 * @param createip
	 *            记录机器IP
	 */
	public void setCreateip(String createip) {
		this.createip = createip;
	}

	/**
	 * Get the 记录机器IP.
	 * 
	 * @return 记录机器IP
	 */
	public String getCreateip() {
		return this.createip;
	}

	/**
	 * Set the 结束时间.
	 * 
	 * @param endtime
	 *            结束时间
	 */
	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	/**
	 * Get the 结束时间.
	 * 
	 * @return 结束时间
	 */
	public String getEndtime() {
		return this.endtime;
	}

	/**
	 * Set the 备注.
	 * 
	 * @param comments
	 *            备注
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * Get the 备注.
	 * 
	 * @return 备注
	 */
	public String getComments() {
		return this.comments;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SystemRunningLogDb other = (SystemRunningLogDb) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
