package ddl;

import java.io.Serializable;

/**
 * Model class of 用户权限表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserAccountAccessDb implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private String id;

	/** 关联表名. */
	private String linkedtable;

	/** 关联表ID. */
	private String linkedid;

	/** 角色列表. */
	private RoleListDb linkedrolelistroleList;

	/** 组权限列表. */
	private GroupAccessListDb linkedgroupaccesslistgroupAccessList;

	/** 菜单列表. */
	private MenuListDb linkedmenulistmenuList;

	/** 创建人(系统用户名称). */
	private String createby;

	/** 创建时间. */
	private String createtime;

	/** 备注. */
	private String comments;

	/**
	 * Constructor.
	 */
	public UserAccountAccessDb() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 关联表名.
	 * 
	 * @param linkedtable
	 *            关联表名
	 */
	public void setLinkedtable(String linkedtable) {
		this.linkedtable = linkedtable;
	}

	/**
	 * Get the 关联表名.
	 * 
	 * @return 关联表名
	 */
	public String getLinkedtable() {
		return this.linkedtable;
	}

	/**
	 * Set the 关联表ID.
	 * 
	 * @param linkedid
	 *            关联表ID
	 */
	public void setLinkedid(String linkedid) {
		this.linkedid = linkedid;
	}

	/**
	 * Get the 关联表ID.
	 * 
	 * @return 关联表ID
	 */
	public String getLinkedid() {
		return this.linkedid;
	}

	/**
	 * Set the 角色列表.
	 * 
	 * @param linkedrolelistroleList
	 *            角色列表
	 */
	public void setLinkedrolelistroleList(RoleListDb linkedrolelistroleList) {
		this.linkedrolelistroleList = linkedrolelistroleList;
	}

	/**
	 * Get the 角色列表.
	 * 
	 * @return 角色列表
	 */
	public RoleListDb getLinkedrolelistroleList() {
		return this.linkedrolelistroleList;
	}

	/**
	 * Set the 组权限列表.
	 * 
	 * @param linkedgroupaccesslistgroupAccessList
	 *            组权限列表
	 */
	public void setLinkedgroupaccesslistgroupAccessList(GroupAccessListDb linkedgroupaccesslistgroupAccessList) {
		this.linkedgroupaccesslistgroupAccessList = linkedgroupaccesslistgroupAccessList;
	}

	/**
	 * Get the 组权限列表.
	 * 
	 * @return 组权限列表
	 */
	public GroupAccessListDb getLinkedgroupaccesslistgroupAccessList() {
		return this.linkedgroupaccesslistgroupAccessList;
	}

	/**
	 * Set the 菜单列表.
	 * 
	 * @param linkedmenulistmenuList
	 *            菜单列表
	 */
	public void setLinkedmenulistmenuList(MenuListDb linkedmenulistmenuList) {
		this.linkedmenulistmenuList = linkedmenulistmenuList;
	}

	/**
	 * Get the 菜单列表.
	 * 
	 * @return 菜单列表
	 */
	public MenuListDb getLinkedmenulistmenuList() {
		return this.linkedmenulistmenuList;
	}

	/**
	 * Set the 创建人(系统用户名称).
	 * 
	 * @param createby
	 *            创建人(系统用户名称)
	 */
	public void setCreateby(String createby) {
		this.createby = createby;
	}

	/**
	 * Get the 创建人(系统用户名称).
	 * 
	 * @return 创建人(系统用户名称)
	 */
	public String getCreateby() {
		return this.createby;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createtime
	 *            创建时间
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public String getCreatetime() {
		return this.createtime;
	}

	/**
	 * Set the 备注.
	 * 
	 * @param comments
	 *            备注
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * Get the 备注.
	 * 
	 * @return 备注
	 */
	public String getComments() {
		return this.comments;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		UserAccountAccessDb other = (UserAccountAccessDb) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
