package com.rick.fssarb.manager.system.bean;

import java.io.Serializable;

/**
 * Model class of group_access.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GroupAccess implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private String id;

	/** 关联组ID. */
	private String linkedgroupid;

	/** 名称. */
	private String name;

	/** 关联访问列表ID. */
	private String linkedaccesslistid;

	/** 关联表名. */
	private String linkedtable;

	/** 关联表ID. */
	private String linkedid;

	/** 创建人(系统用户名称). */
	private String createby;

	/** 创建时间. */
	private String createtime;

	/** 备注. */
	private String comments;

	/**
	 * Constructor.
	 */
	public GroupAccess() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 关联组ID.
	 * 
	 * @param linkedgroupid
	 *            关联组ID
	 */
	public void setLinkedgroupid(String linkedgroupid) {
		this.linkedgroupid = linkedgroupid;
	}

	/**
	 * Get the 关联组ID.
	 * 
	 * @return 关联组ID
	 */
	public String getLinkedgroupid() {
		return this.linkedgroupid;
	}

	/**
	 * Set the 名称.
	 * 
	 * @param name
	 *            名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 名称.
	 * 
	 * @return 名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 关联访问列表ID.
	 * 
	 * @param linkedaccesslistid
	 *            关联访问列表ID
	 */
	public void setLinkedaccesslistid(String linkedaccesslistid) {
		this.linkedaccesslistid = linkedaccesslistid;
	}

	/**
	 * Get the 关联访问列表ID.
	 * 
	 * @return 关联访问列表ID
	 */
	public String getLinkedaccesslistid() {
		return this.linkedaccesslistid;
	}

	/**
	 * Set the 关联表名.
	 * 
	 * @param linkedtable
	 *            关联表名
	 */
	public void setLinkedtable(String linkedtable) {
		this.linkedtable = linkedtable;
	}

	/**
	 * Get the 关联表名.
	 * 
	 * @return 关联表名
	 */
	public String getLinkedtable() {
		return this.linkedtable;
	}

	/**
	 * Set the 关联表ID.
	 * 
	 * @param linkedid
	 *            关联表ID
	 */
	public void setLinkedid(String linkedid) {
		this.linkedid = linkedid;
	}

	/**
	 * Get the 关联表ID.
	 * 
	 * @return 关联表ID
	 */
	public String getLinkedid() {
		return this.linkedid;
	}

	/**
	 * Set the 创建人(系统用户名称).
	 * 
	 * @param createby
	 *            创建人(系统用户名称)
	 */
	public void setCreateby(String createby) {
		this.createby = createby;
	}

	/**
	 * Get the 创建人(系统用户名称).
	 * 
	 * @return 创建人(系统用户名称)
	 */
	public String getCreateby() {
		return this.createby;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createtime
	 *            创建时间
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public String getCreatetime() {
		return this.createtime;
	}

	/**
	 * Set the 备注.
	 * 
	 * @param comments
	 *            备注
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * Get the 备注.
	 * 
	 * @return 备注
	 */
	public String getComments() {
		return this.comments;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		GroupAccess other = (GroupAccess) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
