package com.rick.fssarb.manager.system.bean;

import java.io.Serializable;

/**
 * Model class of system_resource.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SystemResource implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private String id;

	/** 关联表名. */
	private String linkedtable;

	/** 关联表ID. */
	private String linkedid;

	/** 名称. */
	private String name;

	/** 资源绝对路径. */
	private String realpath;

	/** 保存路径. */
	private String savepath;

	/** 访问URL(系统上线使用). */
	private String url;

	/** 缩略图. */
	private String thumbnails;

	/** 创建人(系统用户名称). */
	private String createby;

	/** 创建时间. */
	private String createtime;

	/** 是否启用(0禁用,1启用,默认0). */
	private String enable;

	/** 更新时间. */
	private String updatetime;

	/** 备注. */
	private String comments;

	/**
	 * Constructor.
	 */
	public SystemResource() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 关联表名.
	 * 
	 * @param linkedtable
	 *            关联表名
	 */
	public void setLinkedtable(String linkedtable) {
		this.linkedtable = linkedtable;
	}

	/**
	 * Get the 关联表名.
	 * 
	 * @return 关联表名
	 */
	public String getLinkedtable() {
		return this.linkedtable;
	}

	/**
	 * Set the 关联表ID.
	 * 
	 * @param linkedid
	 *            关联表ID
	 */
	public void setLinkedid(String linkedid) {
		this.linkedid = linkedid;
	}

	/**
	 * Get the 关联表ID.
	 * 
	 * @return 关联表ID
	 */
	public String getLinkedid() {
		return this.linkedid;
	}

	/**
	 * Set the 名称.
	 * 
	 * @param name
	 *            名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 名称.
	 * 
	 * @return 名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 资源绝对路径.
	 * 
	 * @param realpath
	 *            资源绝对路径
	 */
	public void setRealpath(String realpath) {
		this.realpath = realpath;
	}

	/**
	 * Get the 资源绝对路径.
	 * 
	 * @return 资源绝对路径
	 */
	public String getRealpath() {
		return this.realpath;
	}

	/**
	 * Set the 保存路径.
	 * 
	 * @param savepath
	 *            保存路径
	 */
	public void setSavepath(String savepath) {
		this.savepath = savepath;
	}

	/**
	 * Get the 保存路径.
	 * 
	 * @return 保存路径
	 */
	public String getSavepath() {
		return this.savepath;
	}

	/**
	 * Set the 访问URL(系统上线使用).
	 * 
	 * @param url
	 *            访问URL(系统上线使用)
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * Get the 访问URL(系统上线使用).
	 * 
	 * @return 访问URL(系统上线使用)
	 */
	public String getUrl() {
		return this.url;
	}

	/**
	 * Set the 缩略图.
	 * 
	 * @param thumbnails
	 *            缩略图
	 */
	public void setThumbnails(String thumbnails) {
		this.thumbnails = thumbnails;
	}

	/**
	 * Get the 缩略图.
	 * 
	 * @return 缩略图
	 */
	public String getThumbnails() {
		return this.thumbnails;
	}

	/**
	 * Set the 创建人(系统用户名称).
	 * 
	 * @param createby
	 *            创建人(系统用户名称)
	 */
	public void setCreateby(String createby) {
		this.createby = createby;
	}

	/**
	 * Get the 创建人(系统用户名称).
	 * 
	 * @return 创建人(系统用户名称)
	 */
	public String getCreateby() {
		return this.createby;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createtime
	 *            创建时间
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public String getCreatetime() {
		return this.createtime;
	}

	/**
	 * Set the 是否启用(0禁用,1启用,默认0).
	 * 
	 * @param enable
	 *            是否启用(0禁用,1启用,默认0)
	 */
	public void setEnable(String enable) {
		this.enable = enable;
	}

	/**
	 * Get the 是否启用(0禁用,1启用,默认0).
	 * 
	 * @return 是否启用(0禁用,1启用,默认0)
	 */
	public String getEnable() {
		return this.enable;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updatetime
	 *            更新时间
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public String getUpdatetime() {
		return this.updatetime;
	}

	/**
	 * Set the 备注.
	 * 
	 * @param comments
	 *            备注
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * Get the 备注.
	 * 
	 * @return 备注
	 */
	public String getComments() {
		return this.comments;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SystemResource other = (SystemResource) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
